config/routes.rb
Rails.application.routes.draw do
  root "slots#index"

  resources :slots, except: [:index, :edit, :update] do
    collection do
      get :import, to: 'slots#upload_csv'
      post :import
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/importer.rb
class Importer
  attr_reader :errors, :slots

  def initialize(data)
    @data = data
    @run = false
    @errors = false
    @slots = []
  end

  def valid?
    build unless @run
    !errors
  end

  def save
    return unless valid?

    slots.each do |slot|
      slot.save
    end
  end

  private
  def build
    @data.each do |slot_data|
      slot = Slot.new(slot_hash(slot_data))
      @slots << slot
      @errors = true if !slot.valid?
    end
    @run = true
  end

  def slot_hash(data)
    {
      from: data[:from],
      to: data[:to],
      formation_type: data[:formation_type],
      formation_size: data[:formation_size],
      formation_quantity: data[:formation_quantity],
    }
  end
end

app/models/scaler.rb
class Scaler
  def initialize(app_name, type)
    @app_name, @type = app_name, type
  end

  def scale_to(size, quantity)
    heroku.formation.update(@app_name, @type, { size: size, quantity: quantity })
  end

  def current_scale
    heroku.formation.info(@app_name, @type)
  end

  private
  def heroku
    @_heroku ||= PlatformAPI.connect_oauth(ENV['HEROKU_OAUTH'])
  end
end

app/models/scheduler.rb
class Scheduler
  ### Class methods
  def self.schedule(time, type = :up)
    Scheduler.delay_until(time + Scheduler.delay(type))
  end

  def self.scale(id)
    new(Slot.find(id)).scale!
  end

  def self.reset(id)
    new(Slot.find(id)).reset!
  end

  def self.delay(type = :up)
    scaling_time = 0
    if !ENV['SCALING_TIME'].blank?
      scaling_time = ENV['SCALING_TIME'].to_i
    end

    # If we're scaling up, we want to scale before the actual time
    scaling_time = scaling_time * -1 if type == :up
    scaling_time.minutes
  end

  ### Instance methods
  def initialize(slot)
    @slot = slot
  end

  def scale!
    return false if !@slot.scaleable?

    formation = scaler.current_scale
    scaler.scale_to(slot.formation_size, slot.formation_quantity)

    slot.set_initial_values(formation["size"].downcase, formation["quantity"])

    Scheduler.schedule(@slot.to, :down).reset(@slot.id)
  end

  def reset!
    return false if !@slot.resetable?

    scaler.scale_to(slot.formation_initial_size, slot.formation_initial_quantity)
  end

  private

  def slot
    @slot
  end

  def scaler
    @_scaler ||= Scaler.new(app_name, slot.formation_type)
  end

  def app_name
    ENV['HEROKU_APP_NAME']
  end
end

app/models/slot.rb
class Slot < ActiveRecord::Base
  FORMATION_SIZES = ['free', 'hobby', 'standard-1x', 'standard-2x',
                     'performance-m', 'performance-l'].freeze

  ### Validation
  validates :from, :to, :formation_size, :formation_type, :formation_quantity,
    presence: true
  validates :formation_quantity, numericality: { greater_than: 0 }
  validates_inclusion_of :formation_size, in: FORMATION_SIZES,
    message: 'is not a valid formation size.'
  validate :unique_type_period, on: :create
  validate :correct_size_quantity

  ### Scopes
  scope :scheduled, -> {
    where("slots.to > ? ", Time.now())
  }

  ### Callbacks
  after_commit :schedule!, on: :create

  ### Instance methods
  def cancel!
    self.update_attributes(cancelled: true)
  end

  def set_initial_values(size, quantity)
    self.update_attributes(
      formation_initial_size: size,
      formation_initial_quantity: quantity
    )
  end

  def active?
    from <= Time.now && to >= Time.now
  end

  def deletable?
    !cancelled? && !active?
  end

  def scaleable?
    Time.now >= from && Time.now < to && formation_initial_size.nil? &&
      formation_initial_quantity.nil?
  end

  def resetable?
    Time.now >= to && !formation_initial_size.nil? &&
      !formation_initial_quantity.nil?
  end

  def schedule!
    Scheduler.schedule(from).scale(id)
  end

  private
  def unique_type_period
    return unless from.present? && to.present?

    delayed_from = from + Scheduler.delay(:up)
    delayed_to = to + Scheduler.delay(:down)

    from_check = Slot.where(
      from: delayed_from..delayed_to,
      formation_type: formation_type
    ).any?
    to_check = Slot.where(
      to: delayed_from..delayed_to,
      formation_type: formation_type
    ).any?
    check = Slot.where(
      "slots.from <= ? AND slots.to >= ? AND slots.formation_type = ?",
      delayed_from,
      delayed_to,
      formation_type
    ).any?

    if from_check || to_check || check
      errors.add(:base, "There is already an active slot within the given time for this formation type.")
    end
  end

  def correct_size_quantity
    return if formation_size.nil? || formation_quantity.nil?

    if ['free', 'hobby'].include?(formation_size) && formation_quantity > 1
      errors.add(:formation_quantity, "can only be 1 for #{formation_size}.")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate

  private

  def authenticate
    if !ENV['HTTP_AUTH_USER'].blank? && !ENV['HTTP_AUTH_PASS'].blank?
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV['HTTP_AUTH_USER'] && password == ENV['HTTP_AUTH_PASS']
      end
    end
  end

end

app/controllers/slots_controller.rb
require 'csv'

class SlotsController < ApplicationController
  def index
    @slots = Slot.scheduled
  end

  def new
    @slot = Slot.new
  end

  def create
    @slot = Slot.new(slot_params)

    if @slot.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    slot = Slot.find(params[:id])
    slot.cancel! if slot.deletable?

    redirect_to root_path
  end

  def upload_csv
  end

  def import
    importer = Importer.new(CSV.table(import_params[:csv].path))

    if importer.valid?
      importer.save
      redirect_to root_path
    else
      @slots, @errors = importer.slots, true
      render :upload_csv
    end
  end

  private
  def slot_params
    params.require(:slot).permit(:from, :to, :formation_size, :formation_type,
                                :formation_quantity)
  end

  def import_params
    params.require(:upload).permit(:csv)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Heroku Timed Scaler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <div class="nav-wrapper">
      <div class="container">
        <a href="/" class="brand-logo">Heroku Timed Scaler</a>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/slots/index.html.erb
<div class="row">
  <br>
  <%= link_to "New slot", new_slot_path, class: 'btn' %>
  <%= link_to "Import slots", import_slots_path, class: 'btn' %>
</div>

<% if @slots.any? %>
  <table>
    <thead>
      <tr>
        <th>From</th>
        <th>To</th>
        <th>type</th>
        <th>size</th>
        <th>quantity</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% @slots.each do |slot| %>
      <tr class="<% if slot.cancelled? %>red lighten-4<% elsif slot.active? %>green lighten-3<% end %>">
        <td><%= slot.from %></td>
        <td><%= slot.to %></td>
        <td><%= slot.formation_type %></td>
        <td><%= slot.formation_size %></td>
        <td><%= slot.formation_quantity %></td>
        <td>
          <% if slot.deletable? %>
            <%= button_to "CANCEL", slot_path(slot), method: :delete, class: 'btn red darken-4' %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  No scheduled slots.
<% end %>

app/views/slots/new.html.erb
<div class="row">
  <br>
  <%= form_for(@slot, html: { class: 'col s12' }) do |f| %>
    <% if @slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slot.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @slot.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <div class="row">
      <div class="input-field col s6">
        <%= f.label :from, 'From (YYYY-MM-DD HH:MM) UTC', class: 'active'%>
        <%= f.datetime_local_field :from %>
      </div>

      <div class="input-field col s6">
        <%= f.label :to, 'Until (YYYY-MM-DD HH:MM) UTC', class: 'active' %>
        <%= f.datetime_local_field :to %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
        <%= f.label :formation_size, class: 'active' %>
        <%= f.select :formation_size, Slot::FORMATION_SIZES.map { |s| [s, s] }, {}, { class: 'browser-default' } %>
      </div>
      <div class="input-field col s6">
        <%= f.label :formation_type, class: 'active' %>
        <%= f.text_field :formation_type %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
        <%= f.label :formation_quantity, class: 'active' %>
        <%= f.number_field :formation_quantity %>
      </div>
    </div>

    <div class="actions">
      <%= f.submit class: 'btn' %>
    </div>
  <% end %>
</div>

app/views/slots/upload_csv.html.erb
<div class="row">
  <br>
  <%= form_for(:upload, url: import_slots_path, method: :post, html: { class: 'col s12' }) do |f| %>
    <% if @errors %>
      <ul>
      <% @slots.each_with_index do |slot, index| %>
        <% next unless slot.errors.any? %>
        <li>Slot <%= index + 1 %>:
          <ul>
          <% slot.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </li>
      <% end %>
      </ul>
    <% end %>
    <div class="file-field input-field">
      <div class="btn">
        <span>CSV File</span>
        <%= f.file_field :csv %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>

    <div class="actions">
      <%= f.submit "Import time slots", class: 'btn' %>
    </div>
  <% end %>
</div>